import _ from 'lodash';

export const fontAwesomeFreeIcons = [
	'fa-heart',
	'fa-star',
	'fa-circle',
	'fa-square',
	'fa-diamond',
	'fa-triangle',
	'fa-hexagon',
	'fa-plus',
	'fa-minus',
	'fa-times',
	'fa-check',
	'fa-exclamation',

	'fa-key',
	'fa-lock',
	'fa-gem',
	'fa-crown',
	'fa-trophy',
	'fa-gift',
	'fa-bell',
	'fa-book',
	'fa-pen',
	'fa-pencil',
	'fa-scissors',
	'fa-paperclip',
	'fa-thumbtack',
	'fa-magnet',
	'fa-bomb',
	'fa-wrench',
	'fa-hammer',
	'fa-screwdriver',
	'fa-gear',

	'fa-camera',
	'fa-phone',
	'fa-laptop',
	'fa-desktop',
	'fa-tablet',
	'fa-mobile',
	'fa-gamepad',
	'fa-headphones',
	'fa-microphone',
	'fa-tv',
	'fa-radio',
	'fa-battery-full',

	'fa-car',
	'fa-truck',
	'fa-bus',
	'fa-bicycle',
	'fa-motorcycle',
	'fa-plane',
	'fa-helicopter',
	'fa-rocket',
	'fa-ship',
	'fa-anchor',
	'fa-train',
	'fa-subway',

	'fa-tree',
	'fa-leaf',
	'fa-seedling',
	'fa-flower',
	'fa-sun',
	'fa-moon',
	'fa-cloud',
	'fa-snowflake',
	'fa-bolt',
	'fa-fire',
	'fa-water',
	'fa-mountain',

	'fa-cat',
	'fa-dog',
	'fa-fish',
	'fa-bird',
	'fa-horse',
	'fa-frog',
	'fa-spider',
	'fa-bug',
	'fa-butterfly',
	'fa-dove',
	'fa-dragon',
	'fa-hippo',
	'fa-otter',

	'fa-apple',
	'fa-lemon',
	'fa-carrot',
	'fa-pepper-hot',
	'fa-pizza-slice',
	'fa-hamburger',
	'fa-hotdog',
	'fa-ice-cream',
	'fa-cookie',
	'fa-birthday-cake',
	'fa-coffee',
	'fa-wine-glass',
	'fa-beer',
	'fa-cocktail',
	'fa-mug-hot',

	'fa-football',
	'fa-basketball',
	'fa-baseball',
	'fa-tennis-ball',
	'fa-bowling-ball',
	'fa-golf-ball',
	'fa-hockey-puck',
	'fa-dice',
	'fa-chess',
	'fa-puzzle-piece',

	'fa-music',
	'fa-guitar',
	'fa-drum',
	'fa-microphone-alt',
	'fa-headphones-alt',
	'fa-film',
	'fa-video',
	'fa-theater-masks',
	'fa-ticket',
	'fa-palette',

	'fa-home',
	'fa-building',
	'fa-church',
	'fa-hospital',
	'fa-school',
	'fa-store',
	'fa-warehouse',
	'fa-factory',
	'fa-castle',
	'fa-monument',
	'fa-bridge',

	'fa-eye',
	'fa-hand',
	'fa-thumbs-up',
	'fa-thumbs-down',
	'fa-fist-raised',
	'fa-brain',
	'fa-tooth',
	'fa-heartbeat',
	'fa-pills',
	'fa-syringe',

	'fa-hat-wizard',
	'fa-glasses',
	'fa-mask',
	'fa-ring',
	'fa-watch',
	'fa-shoe-prints',
	'fa-tshirt',
	'fa-hat-cowboy',
	'fa-mitten',
	'fa-socks',
	'fa-umbrella',

	'fa-briefcase',
	'fa-toolbox',
	'fa-hard-hat',
	'fa-clipboard',
	'fa-calculator',
	'fa-ruler',
	'fa-compass',
	'fa-microscope',
	'fa-telescope',
	'fa-stethoscope',

	'fa-flag',
	'fa-medal',
	'fa-award',
	'fa-ribbon',
	'fa-certificate',
	'fa-stamp',
	'fa-envelope',
	'fa-box',
	'fa-cube',
	'fa-sphere',
	'fa-prism'
];

export function getRandomIcons(count: number): string[] {
	const shuffled = [...fontAwesomeFreeIcons].sort(() => 0.5 - Math.random());
	return shuffled.slice(0, count);
}

export function getIconPairs(pairCount: number): string[] {
	const selectedIcons = getRandomIcons(pairCount);
	return _.shuffle([...selectedIcons, ...selectedIcons]); // Duplicate for pairs
}
